--drop table if exists rooms CASCADE;
--
--
-- create table rooms (id bigint generated by default as identity, label varchar(255),checked boolean, primary key (rooms_id));
-- insert into rooms (label,checked) values ('room1',true)
--
--

-- insert into patient (age,name,doctor_id,receipt_id) values (23,'Thomas Williams',1,2);


create table rooms (
       id bigint generated by default as identity,
        label varchar(255),
        checked boolean not null,
        primary key (id)
    )

